services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
    restart: always
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - 80:80
    depends_on:
      - backend
